### ISSUE TITLE
[New Idea] Make icons disappear on a cooldown when walked over.

### ISSUE THREAD

**Issue by DerekZil** [lmachens/aeternum-map#147]
I thought of this yesterday, but forgot to post this awesome idea I had.

Make it so when you walk over an icon, the icon will disappears for the cooldown of how long it takes to regen.
This will make farming so much easier for us, we will never walk back to ore/chests we got ever again.

I also recommend you make the icon disappear after 3/5/7 seconds of walking over it, due to us still having to mine/gather.

For example:
Elite Chests = 23 Hour Cooldown
Iron Ore = 10 Minute Cooldown
Etc.

-DAZ

**Comment by DerekZil** [comment]
Or if it grays out or something to, that would work.

**Comment by maxenceconter** [comment]
up

**Comment by yLordMagnus** [comment]
This is something quite complex to implement since different nodes/chests have different respawn times, and that also varies depending on the area, like on Elite zones they have different respawn times.

**Comment by Triadian** [comment]
if im honest i think something like a 5 minute timer just enough to get you out of the area so you know what you did and what you didnt do should be enough, if we start doing exact timings on every node it would get too complex

**Comment by Sturmfunke** [comment]
I find the usability of this feature, as you described it, a bit suboptimal.
I dont want nodes disappear just because I walked over them. It would be irritating if nodes "randomly" vanish from the map when I travel across Aeternum.

**Proposition:** Mark the nearest unfarmed node in a radius of 1 meter as "farmed" for 5 minutes via a red dot appearing in the top left corner of the node icon if I stand still for at least 1 second near this node. (I will have to check what's the shortest time here to farm something, might be a bit under a second.) If the nearest node is already farmed, this rule applies to the next unfarmed node (some hearbs are pretty close to each other).

**Comment by josdemmers** [comment]
Can be closed? We now have a cooldown timer on right click or when pressing hotkey
