### ISSUE TITLE
[Feature Request] Friend Markers/ Locations

### ISSUE THREAD

**Issue by bonxz** [lmachens/aeternum-map#156]
Hello, I saw on the other Overwolf map that you can share a location code with friends so they see always your location. Would something like that be possible here?

**Comment by ChrisonSimtian** [comment]
I've started on that one but its currently on hold since Overwolf said not to add any new/major features.

However to spin that idea a bit further, ideally you'd share your location also with your company or in a group semaphore so that you dont have to add heaps of friends codes but instead only share it once for a certain context (=company, group of friends) and everyone who joins automatically ends up on your minimap

**Comment by Triadian** [comment]
as a plus to that spin, can we add a things just out side the map get pinned to the edge (maybe with a transparent feature for how far away they are) for example if i am at zoom level 2 and if i went to zoom level 3 i could see a team mate they should show on the edge of zoom 2 - so could see which way to go to get them onto my map.

**Comment by lmachens** [comment]
Solved in v1.28.11. Feel free to add new issues based on the comments  you added 👍
