### ISSUE TITLE
Option to toggle one or more customizable circles/areas around player marker.

### ISSUE THREAD

**Issue by Gyoniro** [lmachens/aeternum-map#265]
Idea is to have one or more circles being displayed around the player marker of customizable radius.

Usecase 1 - Healing in War: Having a circle of say 100m or 20m radius around player marker would make it immediate to check which party friend is in range of heals and who's out of said radius.

**Comment by josdemmers** [comment]
Great idea but too risky because New World uses EAC.

Normally this is implemented by hooking into the game memory and reading the required game data.
i.e. player position, camera orientation.
Otherwise you wont be able to draw the circles in the correct size and orientation.

Probably can be closed as it's too risky to implement.

**Comment by josdemmers** [comment]
Maybe reopen this one again. Thought of another way to implement this, or maybe I understood @Gyoniro wrong and this is what he actually meant.

Instead of adding circles around your ingame character to show the spell range. You could add the circles to the map only.
Wont help much if the others are not using the aeternum-map but if they do and you share your position it could be very useful and powerful info to have.
