### ISSUE TITLE
Request: Intelligent zoom mode

### ISSUE THREAD

**Issue by rafek1241** [lmachens/aeternum-map#48]
Intelligent zoom mode.
1. When you step into a settlement -> it zooms in the map.
2. When you step out of a settlement -> zoom out.

Pic rel:
![image](https://user-images.githubusercontent.com/9272027/137541108-393dda3d-133e-44cb-9a8b-06e538969946.png)
![image](https://user-images.githubusercontent.com/9272027/137541112-be7db868-ec5c-487f-be28-3dffdd4f9592.png)

**Comment by Cabola** [comment]
I'd like to request this feature too, was something I had become accustomed to with CptWesley's Minimap! :)

**Comment by nixxou** [comment]
Same for me, it would be really usefull.

**Comment by Sturmfunke** [comment]
I could also see this as a useful feature for the website map if going into settlements would automatically zoom in to the second closest zoom (not the "blurry" one, as it would not show the whole settlement). And when leaving the settlement it zooms out to what the zoom level was before.

TBD: What happens when I change the zoom level manually while being in a settlement? The manually chosen zoom level could stay active when I leave the settlement or it could still switch back to the zoom level that the user had before entering a settlement. Can't say what would feel better.

This could also be done for expeditions. And for the Open Rush map I would suggest the third closest zoom level.

**Comment by Cabola** [comment]
> I could also see this as a useful feature for the website map if going into settlements would automatically zoom in to the second closest zoom (not the "blurry" one, as it would not show the whole settlement).
> 
> TBD: What happens when I change the zoom level manually while being in a settlement? The manually chosen zoom level could stay active when I leave the settlement or it could still switch back to the zoom level that the user had before entering a settlement. Can't say what would feel better.
> 
> This could also be done for Expeditions and the Outpost Rush map. For the Outpost Rush map I would suggest the third closest zoom level.

Could just have a little settings page for zoom level at specific locations and then what ever is done to the map is reset when hitting one of those locations that has a zoom level set.

So say you're in the city, and zoom level is set to 2 as you suggest, outside city it's set to 5. We enter the city it goes to 2, we then manually change zoom level to 4, leave the city and it goes to 5. We run around a bit then return to the city and it goes down to 2 again because that is what we've setup in the settings.

So 4 zoom level settings, one for each of:
- Normal Default
- Settlement
- Expeditions
- Outpost Rush

Could always add more for other locations..

**Comment by lmachens** [comment]
I like to add two zoom levels, one for outside a location, one for inside.
The zoom level will be the last zoom level the user had. 
We only need a single setting to turn on/off adaptive zoom instead.
